### PR TITLE
Update plugin for UE 4.17.x

### PR DESCRIPTION
**Pull request by Goodevil95**
UE 4.17.x asking to enable / disable the plugin at each startup. This pull request resolve this issue.
And update readme:)

### CODE REVIEW

**Comment by fire** [comment]
Will compile linux UE4 editor and check it. If I don't get a chance, I'll merge it in a few days.

**Comment by Goodevil95** [comment]
Hmm... I can't create new C++ project. Is this plugin issue?
<a target="_blank" href="https://itmages.ru/image/view/6051453/defe64b2"></a>

**Comment by fire** [comment]
What version of clang are you using?

**Comment by Goodevil95** [comment]
[4.0.1](https://www.archlinux.org/packages/extra/x86_64/clang/)

**Comment by fire** [comment]
The last time I looked at this, you need to alias the specific clang compiler to `clang`

**Comment by Goodevil95** [comment]
How can I do this?

Did you compile unreal engine with this plugin? Do you get to create C++ projects?

**Comment by fire** [comment]
I hard coded the names of the clang compilers here. https://github.com/fire/QtCreatorSourceCodeAccess/blob/master/Source/QtCreatorSourceCodeAccess/Private/QtCreatorSourceCodeAccessor.cpp#L40

**Comment by Goodevil95** [comment]
Hm... I have clang in bin directory:
```
ls /usr/bin | grep clang
clang
clang++
clang-4.0
clang-check
clang-cl
clang-cpp
clang-format
clang-import-test
clang-offload-bundler
git-clang-format
```

**Comment by fire** [comment]
Try adding 
`|| FPaths::FileExists(TEXT("/usr/bin/clang-4.0"))`

and 

show the results of 
which clang
which clang-4.0

**Comment by Goodevil95** [comment]
Okay, I will try this... But I think it does not help because I have `clang` in /usr/bin
```
[gena@AlienwareM15x ~]$ which clang
/usr/bin/clang
[gena@AlienwareM15x ~]$ which clang-4.0
/usr/bin/clang-4.0
```

**Comment by fire** [comment]
If we can't figure it out we can always return true... there

**Comment by Goodevil95** [comment]
I will compile Unreal Engine tonight and will test plugin:)

**Comment by Goodevil95** [comment]
It helped me! I builded UE 4.17.1 again and added this line into plugin. Now everything works. Thank you:)

**Pull request merged**
